using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RTciv2.Enums
{
    public enum TechType
    {
        AdvFlight = 0,
        Alphabet = 1,
        AmphWarfare = 2,
        Astronomy = 3,
        AtomTheory = 4,
        Automobile = 5,
        Banking = 6,
        BridgeBuild = 7,
        BronzeWork = 8,
        CeremBurial = 9,
        Chemistry = 10,
        Chivalry = 11,
        CodeLaws = 12,
        CombArms = 13,
        Combustion = 14,
        Communism = 15,
        Computers = 16,
        Conscript = 17,
        Construct = 18,
        Corporat = 19,
        Currency = 20,
        Democracy = 21,
        Economics = 22,
        Electricity = 23,
        Electronics = 24,
        Engineering = 25,
        Environment = 26,
        Espionage = 27,
        Explosives = 28,
        Feudalism = 29,
        Flight = 30,
        Fundament = 31,
        FusionPwr = 32,
        GeneticEng = 33,
        GuerillaWar = 34,
        Gunpowder = 35,
        HorsebackRid = 36,
        Industrializ = 37,
        Invention = 38,
        IronWorking = 39,
        LaborUnion = 40,
        Laser = 41,
        Leadership = 42,
        Literacy = 43,
        MachineTools = 44,
        Magnetism = 45,
        MapMaking = 46,
        Masonry = 47,
        MassProd = 48,
        Mathematics = 49,
        Medicine = 50,
        Metallurgy = 51,
        Miniaturiz = 52,
        MobileWarf = 53,
        Monarchy = 54,
        Monoteism = 55,
        Mysticism = 56,
        Navigation = 57,
        NuclearFiss = 58,
        NuclearPwr = 59,
        Philosophy = 60,
        Physics = 61,
        Plastics = 62,
        Plumbing = 63,
        Polytheism = 64,
        Pottery = 65,
        Radio = 66,
        Railroad = 67,
        Recycling = 68,
        Refining = 69,
        Refrigerat = 70,
        Republic = 71,
        Robotics = 72,
        Rocketry = 73,
        Sanitation = 74,
        Seafaring = 75,
        SpaceFlight = 76,
        Stealth = 77,
        SteamEngine = 78,
        Steel = 79,
        Supercond = 80,
        Tactics = 81,
        Theology = 82,
        TheoryGrav = 83,
        Trade = 84,
        University = 85,
        WarriorCode = 86,
        Wheel = 87,
        Writing = 88,
        FutureTech = 89,
        UserDefA = 90,
        UserDefB = 91,
        UserDefC = 92,
        ExtraAdv1 = 93,
        ExtraAdv2 = 94,
        ExtraAdv3 = 95,
        ExtraAdv4 = 96,
        ExtraAdv5 = 97,
        ExtraAdv6 = 98,
        ExtraAdv7 = 99,
        None = 100
    }
}
