using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PoskusCiv2.Enums
{
    public enum UnitType
    {
        Settlers = 0,
        Engineers = 1,
        Warriors = 2,
        Phalanx = 3,
        Archers = 4,
        Legions = 5,
        Pikemen = 6,
        Musketeers = 7,
        Fanatics = 8,
        Partisans = 9,
        AlpineTroops = 10,
        Riflemen = 11,
        Marines = 12,
        Paratroopers = 13,
        MechInf = 14,
        Horsemen = 15,
        Chariot = 16,
        Elephant = 17,
        Crusaders = 18,
        Knights = 19,
        Dragoons = 20,
        Cavalry = 21,
        Armor = 22,
        Catapult = 23,
        Cannon = 24,
        Artillery = 25,
        Howitzer = 26,
        Fighter = 27,
        Bomber = 28,
        Helicopter = 29,
        StlthFtr = 30,
        StlthBmbr = 31,
        Trireme = 32,
        Caravel = 33,
        Galleon = 34,
        Frigate = 35,
        Ironclad = 36,
        Destroyer = 37,
        Cruiser = 38,
        AEGISCruiser = 39,
        Battleship = 40,
        Submarine = 41,
        Carrier = 42,
        Transport = 43,
        CruiseMsl = 44,
        NuclearMsl = 45,
        Diplomat = 46,
        Spy = 47,
        Caravan = 48,
        Freight = 49,
        Explorer = 50,
        Extra1 = 51,
        Extra2 = 52,
        Extra3 = 53,
        Extra4 = 54,
        Extra5 = 55,
        Extra6 = 56,
        Extra7 = 57,
        Extra8 = 58,
        Extra9 = 59,
        Extra10 = 60,
        Extra11 = 61,
        Extra12 = 62
    }
}
